name: Build containers
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  Build-Containers:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: 'Patch gitea'
      working-directory: gitea
      run: |
        git apply ../cockroach.patch
    - name: 'Build default amd64 image'
      working-directory: gitea
      run: |
        docker build . --tag ghcr.io/$(echo "${{github.actor}}" | tr '[:upper:]' '[:lower:]')/gitea-cockroach:latest-amd64
    - name: 'Build rootless amd64 image'
      working-directory: gitea
      run: |
        docker build -f Dockerfile.rootless . --tag ghcr.io/$(echo "${{github.actor}}" | tr '[:upper:]' '[:lower:]')/gitea-cockroach:latest-rootless-amd64
    - name: 'Push images'
      run: |
        docker push ghcr.io/$(echo "${{github.actor}}" | tr '[:upper:]' '[:lower:]')/gitea-cockroach:latest-amd64
        docker push ghcr.io/$(echo "${{github.actor}}" | tr '[:upper:]' '[:lower:]')/gitea-cockroach:latest-rootless-amd64
    #- name: 'Build default arm64 image'
    #- name: 'Build rootless arm64 image'
